In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Data

Link: https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients

In [2]:
data = pd.read_excel("drive/My Drive/colab notebooks/default of credit card clients.xls")

In [3]:
data

Unnamed: 0         X1  ...       X23                           Y
0             ID  LIMIT_BAL  ...  PAY_AMT6  default payment next month
1              1      20000  ...         0                           1
2              2     120000  ...      2000                           1
3              3      90000  ...      5000                           0
4              4      50000  ...      1000                           0
...          ...        ...  ...       ...                         ...
29996      29996     220000  ...      1000                           0
29997      29997     150000  ...         0                           0
29998      29998      30000  ...      3100                           1
29999      29999      80000  ...      1804                           1
30000      30000      50000  ...      1000                           1

[30001 rows x 25 columns]

In [4]:
new_header = data.iloc[0] #grab the first row for the header
data = data[1:] #take the data less the header row
data.columns = new_header #set the header row as the df header

In [5]:
data

0         ID LIMIT_BAL SEX  ... PAY_AMT5 PAY_AMT6 default payment next month
1          1     20000   2  ...        0        0                          1
2          2    120000   2  ...        0     2000                          1
3          3     90000   2  ...     1000     5000                          0
4          4     50000   2  ...     1069     1000                          0
5          5     50000   1  ...      689      679                          0
...      ...       ...  ..  ...      ...      ...                        ...
29996  29996    220000   1  ...     5000     1000                          0
29997  29997    150000   1  ...        0        0                          0
29998  29998     30000   1  ...     2000     3100                          1
29999  29999     80000   1  ...    52964     1804                          1
30000  30000     50000   1  ...     1000     1000                          1

[30000 rows x 25 columns]

In [6]:
data.columns = map(str.lower, data.columns)

In [7]:
data

id limit_bal sex  ... pay_amt5 pay_amt6 default payment next month
1          1     20000   2  ...        0        0                          1
2          2    120000   2  ...        0     2000                          1
3          3     90000   2  ...     1000     5000                          0
4          4     50000   2  ...     1069     1000                          0
5          5     50000   1  ...      689      679                          0
...      ...       ...  ..  ...      ...      ...                        ...
29996  29996    220000   1  ...     5000     1000                          0
29997  29997    150000   1  ...        0        0                          0
29998  29998     30000   1  ...     2000     3100                          1
29999  29999     80000   1  ...    52964     1804                          1
30000  30000     50000   1  ...     1000     1000                          1

[30000 rows x 25 columns]

In [8]:
data['id'].unique()

array([1, 2, 3, ..., 29998, 29999, 30000], dtype=object)

In [9]:
data['education'].unique()

array([2, 1, 3, 5, 4, 6, 0], dtype=object)

In [10]:
data['sex'].unique()

array([2, 1], dtype=object)

In [11]:
data['sex'].value_counts()

2    18112
1    11888
Name: sex, dtype: int64

In [12]:
data['default payment next month'].value_counts()

0    23364
1     6636
Name: default payment next month, dtype: int64

In [13]:
data.dtypes

id                            object
limit_bal                     object
sex                           object
education                     object
marriage                      object
age                           object
pay_0                         object
pay_2                         object
pay_3                         object
pay_4                         object
pay_5                         object
pay_6                         object
bill_amt1                     object
bill_amt2                     object
bill_amt3                     object
bill_amt4                     object
bill_amt5                     object
bill_amt6                     object
pay_amt1                      object
pay_amt2                      object
pay_amt3                      object
pay_amt4                      object
pay_amt5                      object
pay_amt6                      object
default payment next month    object
dtype: object

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 1 to 30000
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype 
---  ------                      --------------  ----- 
 0   id                          30000 non-null  object
 1   limit_bal                   30000 non-null  object
 2   sex                         30000 non-null  object
 3   education                   30000 non-null  object
 4   marriage                    30000 non-null  object
 5   age                         30000 non-null  object
 6   pay_0                       30000 non-null  object
 7   pay_2                       30000 non-null  object
 8   pay_3                       30000 non-null  object
 9   pay_4                       30000 non-null  object
 10  pay_5                       30000 non-null  object
 11  pay_6                       30000 non-null  object
 12  bill_amt1                   30000 non-null  object
 13  bill_amt2                   30000 non-null  ob

In [15]:
data['pay_0'].unique()

array([2, -1, 0, -2, 1, 3, 4, 8, 7, 5, 6], dtype=object)

# Data Preparation

In [40]:
def preprocess_inputs(df):
  df = df.copy()

  #drop id
  df = df.drop("id", axis=1)

  #converting object column to int columns (continuous variables)
  df['limit_bal'] = df['limit_bal'].astype(str).astype(int)
  df['age'] = df['age'].astype(str).astype(int)
  df['bill_amt1'] = df['bill_amt1'].astype(str).astype(int)
  df['bill_amt2'] = df['bill_amt2'].astype(str).astype(int)
  df['bill_amt3'] = df['bill_amt3'].astype(str).astype(int)
  df['bill_amt4'] = df['bill_amt4'].astype(str).astype(int)
  df['bill_amt5'] = df['bill_amt5'].astype(str).astype(int)
  df['bill_amt6'] = df['bill_amt6'].astype(str).astype(int)
  df['pay_amt1'] = df['pay_amt1'].astype(str).astype(int)
  df['pay_amt2'] = df['pay_amt2'].astype(str).astype(int)
  df['pay_amt3'] = df['pay_amt3'].astype(str).astype(int)
  df['pay_amt4'] = df['pay_amt4'].astype(str).astype(int)
  df['pay_amt5'] = df['pay_amt5'].astype(str).astype(int)
  df['pay_amt6'] = df['pay_amt6'].astype(str).astype(int)

  #rename the last column
  df.rename(columns={'default payment next month': 'label'}, inplace = True)



  return df

In [41]:
X = preprocess_inputs(data)

In [42]:
X

limit_bal sex education marriage  ...  pay_amt4 pay_amt5 pay_amt6 label
1          20000   2         2        1  ...         0        0        0     1
2         120000   2         2        2  ...      1000        0     2000     1
3          90000   2         2        2  ...      1000     1000     5000     0
4          50000   2         2        1  ...      1100     1069     1000     0
5          50000   1         2        1  ...      9000      689      679     0
...          ...  ..       ...      ...  ...       ...      ...      ...   ...
29996     220000   1         3        1  ...      3047     5000     1000     0
29997     150000   1         3        2  ...       129        0        0     0
29998      30000   1         2        2  ...      4200     2000     3100     1
29999      80000   1         3        1  ...      1926    52964     1804     1
30000      50000   1         2        1  ...      1000     1000     1000     1

[30000 rows x 24 columns]

In [43]:
X.dtypes

limit_bal     int64
sex          object
education    object
marriage     object
age           int64
pay_0        object
pay_2        object
pay_3        object
pay_4        object
pay_5        object
pay_6        object
bill_amt1     int64
bill_amt2     int64
bill_amt3     int64
bill_amt4     int64
bill_amt5     int64
bill_amt6     int64
pay_amt1      int64
pay_amt2      int64
pay_amt3      int64
pay_amt4      int64
pay_amt5      int64
pay_amt6      int64
label        object
dtype: object

# Using PyCaret

In [44]:
!pip install pycaret

     |████████████████████████████████| 266kB 18.3MB/s 
     |████████████████████████████████| 81kB 6.8MB/s 
     |████████████████████████████████| 102kB 10.4MB/s 
     |████████████████████████████████| 215kB 52.2MB/s 
     |████████████████████████████████| 14.2MB 275kB/s 
     |████████████████████████████████| 1.7MB 40.4MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 61kB 7.3MB/s 
     |████████████████████████████████| 6.8MB 46.6MB/s 
     |████████████████████████████████| 2.0MB 46.8MB/s 
     |████████████████████████████████| 276kB 51.2MB/s 
     |████████████████████████████████| 245kB 48.4MB/s 
     |████████████████████████████████| 1.2MB 43.7MB/s 
     |████████████████████████████████| 378kB 44.7MB/s 
     |████████████████████████████████| 163kB 41.4MB/s 
     |████████████████████████████████| 153kB 43.1M

In [45]:
import pycaret.classification as pyc

In [46]:
pyc.setup(
    data = X,
    target = 'label',
    train_size = 0.7,
    normalize = True
)

Description             Value
0                               session_id              8445
1                                   Target             label
2                              Target Type            Binary
3                            Label Encoded        0: 0, 1: 1
4                            Original Data       (30000, 24)
5                           Missing Values             False
6                         Numeric Features                14
7                     Categorical Features                 9
8                         Ordinal Features             False
9                High Cardinality Features             False
10                 High Cardinality Method              None
11                   Transformed Train Set       (20999, 89)
12                    Transformed Test Set        (9001, 89)
13                      Shuffle Train-Test              True
14                     Stratify Train-Test             False
15                          Fold Generator   StratifiedKFold
16                             Fold Number                10
17                                CPU Jobs                -1
18                                 Use GPU             False
19                          Log Experiment             False
20                         Experiment Name  clf-default-name
21                                     USI              98d4
22                         Imputation Type            simple
23          Iterative Imputation Iteration              None
24                         Numeric Imputer              mean
25      Iterative Imputation Numeric Model              None
26                     Categorical Imputer          constant
27  Iterative Imputation Categorical Model              None
28           Unknown Categoricals Handling    least_frequent
29                               Normalize              True
30                        Normalize Method            zscore
31                          Transformation             False
32                   Transformation Method              None
33                                     PCA             False
34                              PCA Method              None
35                          PCA Components              None
36                     Ignore Low Variance             False
37                     Combine Rare Levels             False
38                    Rare Level Threshold              None
39                         Numeric Binning             False
40                         Remove Outliers             False
41                      Outliers Threshold              None
42                Remove Multicollinearity             False
43             Multicollinearity Threshold              None
44                              Clustering             False
45                    Clustering Iteration              None
46                     Polynomial Features             False
47                       Polynomial Degree              None
48                    Trignometry Features             False
49                    Polynomial Threshold              None
50                          Group Features             False
51                       Feature Selection             False
52                Feature Selection Method           classic
53            Features Selection Threshold              None
54                     Feature Interaction             False
55                           Feature Ratio             False
56                   Interaction Threshold              None
57                           Fix Imbalance             False
58                    Fix Imbalance Method             SMOTE

(False, 18519    1
 15324    0
 1706     1
 11653    0
 22309    0
         ..
 7351     0
 23252    0
 15523    0
 28769    0
 10737    0
 Name: label, Length: 20999, dtype: int64, {'USI',
  'X',
  'X_test',
  'X_train',
  '_all_metrics',
  '_all_models',
  '_all_models_internal',
  '_available_plots',
  '_gpu_n_jobs_param',
  '_internal_pipeline',
  '_ml_usecase',
  'create_model_container',
  'data_before_preprocess',
  'display_container',
  'exp_name_log',
  'experiment__',
  'fix_imbalance_method_param',
  'fix_imbalance_param',
  'fold_generator',
  'fold_groups_param',
  'fold_param',
  'fold_shuffle_param',
  'gpu_param',
  'html_param',
  'imputation_classifier',
  'imputation_regressor',
  'iterative_imputation_iters_param',
  'log_plots_param',
  'logging_param',
  'master_model_container',
  'n_jobs_param',
  'prep_pipe',
  'pycaret_globals',
  'seed',
  'stratify_param',
  'target_param',
  'transform_target_method_param',
  'transform_target_param',
  'y',
  'y_test',
  

In [47]:
pyc.compare_models()

Model  Accuracy     AUC  Recall   Prec.  \
lr                    Logistic Regression    0.8201  0.7700  0.3560  0.6857   
ridge                    Ridge Classifier    0.8194  0.0000  0.3541  0.6824   
lda          Linear Discriminant Analysis    0.8192  0.7664  0.3742  0.6682   
gbc          Gradient Boosting Classifier    0.8189  0.7818  0.3567  0.6786   
svm                   SVM - Linear Kernel    0.8181  0.0000  0.3253  0.6970   
lightgbm  Light Gradient Boosting Machine    0.8170  0.7794  0.3648  0.6620   
ada                  Ada Boost Classifier    0.8161  0.7736  0.3370  0.6751   
rf               Random Forest Classifier    0.8152  0.7658  0.3661  0.6529   
et                 Extra Trees Classifier    0.8062  0.7444  0.3725  0.6060   
nb                            Naive Bayes    0.7977  0.7390  0.1897  0.6597   
knn                K Neighbors Classifier    0.7938  0.6998  0.3422  0.5618   
dt               Decision Tree Classifier    0.7245  0.6160  0.4195  0.3903   
qda       Quadratic Discriminant Analysis    0.6099  0.5398  0.4133  0.2660   

              F1   Kappa     MCC  TT (Sec)  
lr        0.4684  0.3731  0.4023     1.386  
ridge     0.4660  0.3703  0.3993     0.059  
lda       0.4794  0.3806  0.4041     0.386  
gbc       0.4673  0.3708  0.3988     7.470  
svm       0.4434  0.3516  0.3882     0.386  
lightgbm  0.4700  0.3707  0.3949     0.533  
ada       0.4493  0.3536  0.3844     1.698  
rf        0.4688  0.3676  0.3903     3.875  
et        0.4611  0.3513  0.3668     3.352  
nb        0.2927  0.2160  0.2738     0.055  
knn       0.4249  0.3084  0.3226    12.213  
dt        0.4043  0.2255  0.2257     0.473  
qda       0.3173  0.0679  0.0715     0.215

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=8445, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
best_model = pyc.create_model('lr')

Accuracy     AUC  Recall   Prec.      F1   Kappa     MCC
0       0.8267  0.7829  0.3753  0.7126  0.4916  0.3990  0.4289
1       0.8081  0.7517  0.3134  0.6447  0.4218  0.3229  0.3531
2       0.8129  0.7613  0.3184  0.6682  0.4313  0.3357  0.3688
3       0.8186  0.7446  0.3739  0.6654  0.4788  0.3793  0.4024
4       0.8371  0.7962  0.3953  0.7582  0.5197  0.4331  0.4664
5       0.8248  0.7832  0.3868  0.6908  0.4959  0.3999  0.4246
6       0.8186  0.7877  0.3419  0.6867  0.4565  0.3620  0.3937
7       0.8100  0.7406  0.3184  0.6507  0.4275  0.3293  0.3596
8       0.8219  0.7770  0.3632  0.6911  0.4762  0.3812  0.4098
9       0.8228  0.7751  0.3739  0.6890  0.4848  0.3889  0.4154
Mean    0.8201  0.7700  0.3560  0.6857  0.4684  0.3731  0.4023
SD      0.0082  0.0183  0.0290  0.0311  0.0312  0.0336  0.0331

In [49]:
pyc.evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [53]:
unseen_data = X.iloc[[1,2,3], :-1]

In [54]:
unseen_data

limit_bal sex education marriage  ...  pay_amt3 pay_amt4 pay_amt5 pay_amt6
2     120000   2         2        2  ...      1000     1000        0     2000
3      90000   2         2        2  ...      1000     1000     1000     5000
4      50000   2         2        1  ...      1200     1100     1069     1000

[3 rows x 23 columns]

In [55]:
pyc.predict_model(best_model, data = unseen_data)

limit_bal sex education marriage  ...  pay_amt5 pay_amt6 Label   Score
2     120000   2         2        2  ...         0     2000     0  0.7286
3      90000   2         2        2  ...      1000     5000     0  0.8955
4      50000   2         2        1  ...      1069     1000     0  0.8467

[3 rows x 25 columns]